training_pipeline_config:
  pipeline_name: housing
  artifact_dir: artifact

data_ingestion_config:
  data_dir : data
  raw_data_dir: rawData
  ingested_dir: ingestedData

data_validation_config:
  data_dir : data
  schema_dir: config
  schema_file_name: schema.yaml
  validated_dir: validatedData

data_transformation_config:
  data_dir : data
  transformed_dir: transformedData
  transformed_train_dir: trainData
  transformed_test_dir: testData
  preprocessor_dir: preprocessorObject
  test_size: 0.3
  random_state: 42
  
model_trainer_config:
  data_dir: data
  modelc_performance_dir: modelcPerformance
  modelr_performance_dir: modelrPerformance
  model_dir: model
  trained_model_dir: trainedModel
  model_config_dir: config
  modelc_config_file_name: modelc.yaml
  modelr_config_file_name: modelr.yaml
  test_size: 0.3
  random_state: 42


model_evaluator_config:
  model_evaluation_file_name: model_evaluation.yaml
  model_config_dir: config
  model_config_file_name: model.yaml
  model_dir: model
  evaluated_model_file_path: bestEvaluatedModel
  

model_pusher_config:
  model_export_dir: saved_models